// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnsJCWvDT_78SopoGRXtnZndHPbEud_s',
    appId: '1:445486729376:web:a536093d50e6cd3ce0a1c5',
    messagingSenderId: '445486729376',
    projectId: 'quiz-8aac5',
    authDomain: 'quiz-8aac5.firebaseapp.com',
    storageBucket: 'quiz-8aac5.appspot.com',
    measurementId: 'G-5PZY4RC35X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeilIHSR_cw9_DLycPYiXHdUq3VAuPY4',
    appId: '1:445486729376:android:3b33c97b52f0bb1ae0a1c5',
    messagingSenderId: '445486729376',
    projectId: 'quiz-8aac5',
    storageBucket: 'quiz-8aac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnDoYrF2f4AcL5ja4XM_qAlB25F8qkhk',
    appId: '1:445486729376:ios:dc32a011be255901e0a1c5',
    messagingSenderId: '445486729376',
    projectId: 'quiz-8aac5',
    storageBucket: 'quiz-8aac5.appspot.com',
    iosBundleId: 'com.example.quize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMnDoYrF2f4AcL5ja4XM_qAlB25F8qkhk',
    appId: '1:445486729376:ios:dc32a011be255901e0a1c5',
    messagingSenderId: '445486729376',
    projectId: 'quiz-8aac5',
    storageBucket: 'quiz-8aac5.appspot.com',
    iosBundleId: 'com.example.quize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSnsJCWvDT_78SopoGRXtnZndHPbEud_s',
    appId: '1:445486729376:web:01273e0bcdb21d8de0a1c5',
    messagingSenderId: '445486729376',
    projectId: 'quiz-8aac5',
    authDomain: 'quiz-8aac5.firebaseapp.com',
    storageBucket: 'quiz-8aac5.appspot.com',
    measurementId: 'G-55XTPXC7SY',
  );
}
